CREATE TABLE post_items (
                            id bigint generated by default as identity
                                primary key,

                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                            created_by BIGINT,
                            updated_by BIGINT,

                            is_active BOOLEAN DEFAULT TRUE,

                            post_id          bigint       not null
                                constraint fktao5t1y186co1arx03hlqgbd
                                    references posts,

                            uploaded_by_user_id BIGINT NOT NULL,

                            title VARCHAR(255),
                            description TEXT,
                            alt_text VARCHAR(255),

                            item_type VARCHAR(50) NOT NULL,

                            file_url VARCHAR(500) NOT NULL,
                            thumbnail_url VARCHAR(500),
                            file_name VARCHAR(255) NOT NULL,
                            original_file_name VARCHAR(255),
                            file_size_bytes BIGINT,
                            mime_type VARCHAR(255),

                            width INT,
                            height INT,
                            aspect_ratio VARCHAR(50),

                            duration_seconds INT,
                            video_format VARCHAR(100),
                            video_codec VARCHAR(100),
                            bitrate INT,
                            frame_rate DOUBLE PRECISION,

                            camera_make VARCHAR(100),
                            camera_model VARCHAR(100),
                            taken_at TIMESTAMP,
                            location_name VARCHAR(255),
                            latitude DOUBLE PRECISION,
                            longitude DOUBLE PRECISION,

                            sort_order INT DEFAULT 0,
                            is_featured BOOLEAN DEFAULT FALSE,
                            is_cover BOOLEAN DEFAULT FALSE,

                            tags TEXT,
                            color_palette TEXT,

                            view_count BIGINT DEFAULT 0,
                            download_count BIGINT DEFAULT 0,
                            like_count BIGINT DEFAULT 0,

                            processing_status VARCHAR(50) DEFAULT 'PENDING',
                            processing_error TEXT,
                            processed_at TIMESTAMP,

                            is_moderated BOOLEAN DEFAULT FALSE,
                            moderation_score DOUBLE PRECISION,
                            moderation_labels TEXT,
                            is_flagged BOOLEAN DEFAULT FALSE,
                            flag_reason TEXT,

                            CONSTRAINT fk_post_items_post FOREIGN KEY (post_id) REFERENCES posts(id),
                            CONSTRAINT fk_post_items_uploaded_by_user FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id)
);

-- created_at için auto-update trigger (PostgreSQL’de update timestamp otomatik artmaz)
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_post_items_modtime
    BEFORE UPDATE ON post_items
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();
