CREATE TABLE conversations (
                               id bigint generated by default as identity
                                   primary key,
                               user_id BIGINT,
                               conversation_type VARCHAR(50) NOT NULL,
                               status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
                               form_data TEXT,
                               is_form_submitted BOOLEAN DEFAULT FALSE,
                               last_message_at TIMESTAMP,
                               completed_at TIMESTAMP,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               created_by BIGINT,
                               updated_by BIGINT,
                               is_active BOOLEAN DEFAULT TRUE,

                               CONSTRAINT fk_conversations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_conversations_user_id ON conversations(user_id);
CREATE INDEX idx_conversations_status ON conversations(status);
CREATE INDEX idx_conversations_type ON conversations(conversation_type);
CREATE INDEX idx_conversations_last_message ON conversations(last_message_at DESC);



CREATE TABLE conversation_messages (
                                       id bigint generated by default as identity
                                           primary key,
                                       conversation_id BIGINT NOT NULL,
                                       role VARCHAR(20) NOT NULL,
                                       content TEXT NOT NULL,
                                       extracted_data TEXT,
                                       token_count INTEGER,
                                       processing_time_ms BIGINT,
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       created_by BIGINT,
                                       updated_by BIGINT,
                                       is_active BOOLEAN DEFAULT TRUE,

                                       CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
);

CREATE INDEX idx_messages_conversation_id ON conversation_messages(conversation_id);
CREATE INDEX idx_messages_created_at ON conversation_messages(created_at);
CREATE INDEX idx_messages_role ON conversation_messages(role);



CREATE TABLE form_submissions (
                                  id bigint generated by default as identity
                                      primary key,
                                  conversation_id BIGINT NOT NULL UNIQUE,
                                  user_id BIGINT NOT NULL,
                                  city VARCHAR(100),
                                  district VARCHAR(100),
                                  institution_type VARCHAR(50),
                                  school_properties TEXT,
                                  min_price DECIMAL(10, 2),
                                  max_price DECIMAL(10, 2),
                                  explain TEXT,
                                  raw_form_data TEXT,
                                  search_results_count INTEGER,
                                  submitted_at TIMESTAMP,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  created_by BIGINT,
                                  updated_by BIGINT,
                                  is_active BOOLEAN DEFAULT TRUE,

                                  CONSTRAINT fk_submissions_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
                                  CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_submissions_user_id ON form_submissions(user_id);
CREATE INDEX idx_submissions_city ON form_submissions(city);
CREATE INDEX idx_submissions_institution_type ON form_submissions(institution_type);
CREATE INDEX idx_submissions_submitted_at ON form_submissions(submitted_at DESC);

