-- Supply Chain Management System - Database Migration
-- Version: 1.0
-- Description: Creates all tables for supply chain management including suppliers, products, RFQs, quotations, and orders

-- ============================================================================
-- 1. SUPPLIERS TABLE (Independent - No Foreign Keys)
-- ============================================================================
CREATE TABLE suppliers (
                           id bigint generated by default as identity
        primary key,
                           company_name VARCHAR(255) NOT NULL,
                           tax_number VARCHAR(255) NOT NULL UNIQUE,
                           email VARCHAR(255) NOT NULL,
                           phone VARCHAR(255) NOT NULL,
                           address TEXT,
                           is_active BOOLEAN NOT NULL DEFAULT TRUE,
                           description TEXT,
                           average_rating DECIMAL(2, 1) DEFAULT 0.0,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP,
                           created_by BIGINT,
                           updated_by BIGINT
);

CREATE INDEX idx_suppliers_tax_number ON suppliers(tax_number);
CREATE INDEX idx_suppliers_is_active ON suppliers(is_active);

-- ============================================================================
-- 2. CATEGORIES TABLE (Self-referencing)
-- ============================================================================
CREATE TABLE categories (
                            id bigint generated by default as identity
        primary key,
                            name VARCHAR(255) NOT NULL,
                            description TEXT,
                            parent_id BIGINT,
                            is_active BOOLEAN NOT NULL DEFAULT TRUE,
                            display_order INTEGER DEFAULT 0,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP,
                            created_by BIGINT,
                            updated_by BIGINT,
                            CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_categories_parent_id ON categories(parent_id);
CREATE INDEX idx_categories_is_active ON categories(is_active);
CREATE INDEX idx_categories_display_order ON categories(display_order);

-- ============================================================================
-- 3. CATEGORY ATTRIBUTES TABLE (Depends on Categories)
-- ============================================================================
CREATE TABLE category_attributes (
                                     id bigint generated by default as identity
        primary key,
                                     category_id BIGINT NOT NULL,
                                     attribute_name VARCHAR(255) NOT NULL,
                                     possible_values TEXT,
                                     is_required BOOLEAN NOT NULL DEFAULT FALSE,
                                     display_order INTEGER DEFAULT 0,
                                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at TIMESTAMP,
                                     created_by BIGINT,
                                     updated_by BIGINT,
                                     is_active BOOLEAN DEFAULT TRUE,
                                     CONSTRAINT fk_category_attributes_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_category_attributes_category_id ON category_attributes(category_id);
CREATE INDEX idx_category_attributes_display_order ON category_attributes(display_order);

-- ============================================================================
-- 4. PRODUCTS TABLE (Depends on Suppliers and Categories)
-- ============================================================================
CREATE TABLE products (
                          id bigint generated by default as identity
        primary key,
                          supplier_id BIGINT NOT NULL,
                          category_id BIGINT NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          sku VARCHAR(255) UNIQUE,
                          description TEXT,
                          technical_specs TEXT,
                          status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
                          stock_tracking_type VARCHAR(50) NOT NULL DEFAULT 'LIMITED',
                          stock_quantity INTEGER DEFAULT 0,
                          min_stock_level INTEGER DEFAULT 0,
                          base_price DECIMAL(10, 2) NOT NULL,
                          currency VARCHAR(10) NOT NULL DEFAULT 'TRY',
                          tax_rate DECIMAL(5, 2) NOT NULL DEFAULT 20.00,
                          min_order_quantity INTEGER DEFAULT 1,
                          delivery_days INTEGER DEFAULT 7,
                          main_image_url TEXT,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP,
                          created_by BIGINT,
                          updated_by BIGINT,
                          is_active BOOLEAN DEFAULT TRUE,
                          CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
                          CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
);

CREATE INDEX idx_products_supplier_id ON products(supplier_id);
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_status ON products(status);
CREATE INDEX idx_products_is_active ON products(is_active);

-- ============================================================================
-- 5. PRODUCT ATTRIBUTES TABLE (Depends on Products)
-- ============================================================================
CREATE TABLE product_attributes (
                                    id bigint generated by default as identity
        primary key,
                                    product_id BIGINT NOT NULL,
                                    attribute_name VARCHAR(255) NOT NULL,
                                    attribute_value VARCHAR(255) NOT NULL,
                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP,
                                    created_by BIGINT,
                                    updated_by BIGINT,
                                    is_active BOOLEAN DEFAULT TRUE,
                                    CONSTRAINT fk_product_attributes_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_attributes_product_id ON product_attributes(product_id);

-- ============================================================================
-- 6. PRODUCT IMAGES TABLE (Depends on Products)
-- ============================================================================
CREATE TABLE product_images (
                                id bigint generated by default as identity
        primary key,
                                product_id BIGINT NOT NULL,
                                image_url TEXT NOT NULL,
                                display_order INTEGER DEFAULT 0,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP,
                                created_by BIGINT,
                                updated_by BIGINT,
                                is_active BOOLEAN DEFAULT TRUE,
                                CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_images_product_id ON product_images(product_id);
CREATE INDEX idx_product_images_display_order ON product_images(display_order);

-- ============================================================================
-- 7. PRODUCT VARIANTS TABLE (Depends on Products)
-- ============================================================================
CREATE TABLE product_variants (
                                  id bigint generated by default as identity
        primary key,
                                  product_id BIGINT NOT NULL,
                                  variant_name VARCHAR(255) NOT NULL,
                                  sku VARCHAR(255),
                                  price_adjustment DECIMAL(10, 2) DEFAULT 0.00,
                                  stock_quantity INTEGER DEFAULT 0,
                                  is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP,
                                  created_by BIGINT,
                                  updated_by BIGINT,
                                  CONSTRAINT fk_product_variants_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX idx_product_variants_is_active ON product_variants(is_active);

-- ============================================================================
-- 8. PRODUCT DOCUMENTS TABLE (Depends on Products)
-- ============================================================================
CREATE TABLE product_documents (
                                   id bigint generated by default as identity
        primary key,
                                   product_id BIGINT NOT NULL,
                                   document_name VARCHAR(255) NOT NULL,
                                   document_url TEXT NOT NULL,
                                   document_type VARCHAR(50),
                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP,
                                   created_by BIGINT,
                                   updated_by BIGINT,
                                   is_active BOOLEAN DEFAULT TRUE,
                                   CONSTRAINT fk_product_documents_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_documents_product_id ON product_documents(product_id);
CREATE INDEX idx_product_documents_document_type ON product_documents(document_type);

-- ============================================================================
-- 9. PRODUCT DISCOUNTS TABLE (Depends on Products)
-- ============================================================================
CREATE TABLE product_discounts (
                                   id bigint generated by default as identity
        primary key,
                                   product_id BIGINT NOT NULL,
                                   discount_name VARCHAR(255) NOT NULL,
                                   discount_type VARCHAR(50) NOT NULL,
                                   discount_value DECIMAL(10, 2),
                                   min_quantity INTEGER,
                                   max_quantity INTEGER,
                                   start_date DATE,
                                   end_date DATE,
                                   is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP,
                                   created_by BIGINT,
                                   updated_by BIGINT,
                                   CONSTRAINT fk_product_discounts_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_discounts_product_id ON product_discounts(product_id);
CREATE INDEX idx_product_discounts_dates ON product_discounts(start_date, end_date);
CREATE INDEX idx_product_discounts_is_active ON product_discounts(is_active);

-- ============================================================================
-- 10. WISHLISTS TABLE (Depends on Users and Products)
-- Note: Assumes users table already exists with id column
-- ============================================================================
CREATE TABLE wishlists (
                           id bigint generated by default as identity
        primary key,
                           user_id BIGINT NOT NULL,
                           product_id BIGINT NOT NULL,
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP,
                           created_by BIGINT,
                           updated_by BIGINT,
                           is_active BOOLEAN DEFAULT TRUE,
                           CONSTRAINT fk_wishlists_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                           CONSTRAINT uk_wishlists_user_product UNIQUE (user_id, product_id)
);

CREATE INDEX idx_wishlists_user_id ON wishlists(user_id);
CREATE INDEX idx_wishlists_product_id ON wishlists(product_id);

-- ============================================================================
-- 11. RFQs TABLE (Request for Quotation)
-- Note: Assumes campuses table exists (company_id references campuses)
-- ============================================================================
CREATE TABLE rfqs (
                      id bigint generated by default as identity
        primary key,
                      company_id BIGINT NOT NULL,
                      title VARCHAR(255) NOT NULL,
                      description TEXT,
                      rfq_type VARCHAR(50) NOT NULL DEFAULT 'OPEN',
                      status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
                      submission_deadline DATE NOT NULL,
                      expected_delivery_date DATE,
                      payment_terms TEXT,
                      evaluation_criteria TEXT,
                      technical_requirements TEXT,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP,
                      created_by BIGINT,
                      updated_by BIGINT,
                      is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_rfqs_company_id ON rfqs(company_id);
CREATE INDEX idx_rfqs_status ON rfqs(status);
CREATE INDEX idx_rfqs_submission_deadline ON rfqs(submission_deadline);

-- ============================================================================
-- 12. RFQ ITEMS TABLE (Depends on RFQs and Categories)
-- ============================================================================
CREATE TABLE rfq_items (
                           id bigint generated by default as identity
        primary key,
                           rfq_id BIGINT NOT NULL,
                           category_id BIGINT,
                           item_name VARCHAR(255) NOT NULL,
                           specifications TEXT,
                           quantity INTEGER NOT NULL,
                           unit VARCHAR(50),
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP,
                           created_by BIGINT,
                           updated_by BIGINT,
                           is_active BOOLEAN DEFAULT TRUE,
                           CONSTRAINT fk_rfq_items_rfq FOREIGN KEY (rfq_id) REFERENCES rfqs(id) ON DELETE CASCADE,
                           CONSTRAINT fk_rfq_items_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE INDEX idx_rfq_items_rfq_id ON rfq_items(rfq_id);
CREATE INDEX idx_rfq_items_category_id ON rfq_items(category_id);

-- ============================================================================
-- 13. RFQ INVITATIONS TABLE (Depends on RFQs and Suppliers)
-- ============================================================================
CREATE TABLE rfq_invitations (
                                 id bigint generated by default as identity
        primary key,
                                 rfq_id BIGINT NOT NULL,
                                 supplier_id BIGINT NOT NULL,
                                 invited_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP,
                                 created_by BIGINT,
                                 updated_by BIGINT,
                                 is_active BOOLEAN DEFAULT TRUE,
                                 CONSTRAINT fk_rfq_invitations_rfq FOREIGN KEY (rfq_id) REFERENCES rfqs(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_rfq_invitations_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
                                 CONSTRAINT uk_rfq_invitations_rfq_supplier UNIQUE (rfq_id, supplier_id)
);

CREATE INDEX idx_rfq_invitations_rfq_id ON rfq_invitations(rfq_id);
CREATE INDEX idx_rfq_invitations_supplier_id ON rfq_invitations(supplier_id);

-- ============================================================================
-- 14. QUOTATIONS TABLE (Depends on RFQs and Suppliers)
-- ============================================================================
CREATE TABLE quotations (
                            id bigint generated by default as identity
        primary key,
                            rfq_id BIGINT NOT NULL,
                            supplier_id BIGINT NOT NULL,
                            status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
                            total_amount DECIMAL(10, 2),
                            currency VARCHAR(10) DEFAULT 'TRY',
                            valid_until DATE,
                            delivery_days INTEGER,
                            payment_terms TEXT,
                            warranty_terms TEXT,
                            notes TEXT,
                            version_number INTEGER DEFAULT 1,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP,
                            created_by BIGINT,
                            updated_by BIGINT,
                            is_active BOOLEAN DEFAULT TRUE,
                            CONSTRAINT fk_quotations_rfq FOREIGN KEY (rfq_id) REFERENCES rfqs(id) ON DELETE CASCADE,
                            CONSTRAINT fk_quotations_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
);

CREATE INDEX idx_quotations_rfq_id ON quotations(rfq_id);
CREATE INDEX idx_quotations_supplier_id ON quotations(supplier_id);
CREATE INDEX idx_quotations_status ON quotations(status);

-- ============================================================================
-- 15. QUOTATION ITEMS TABLE (Depends on Quotations, RFQ Items, and Products)
-- ============================================================================
CREATE TABLE quotation_items (
                                 id bigint generated by default as identity
        primary key,
                                 quotation_id BIGINT NOT NULL,
                                 rfq_item_id BIGINT,
                                 product_id BIGINT,
                                 item_name VARCHAR(255) NOT NULL,
                                 quantity INTEGER NOT NULL,
                                 unit_price DECIMAL(10, 2) NOT NULL,
                                 discount_amount DECIMAL(10, 2) DEFAULT 0.00,
                                 total_price DECIMAL(10, 2) NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP,
                                 created_by BIGINT,
                                 updated_by BIGINT,
                                 is_active BOOLEAN DEFAULT TRUE,
                                 CONSTRAINT fk_quotation_items_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_quotation_items_rfq_item FOREIGN KEY (rfq_item_id) REFERENCES rfq_items(id) ON DELETE SET NULL,
                                 CONSTRAINT fk_quotation_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

CREATE INDEX idx_quotation_items_quotation_id ON quotation_items(quotation_id);
CREATE INDEX idx_quotation_items_rfq_item_id ON quotation_items(rfq_item_id);
CREATE INDEX idx_quotation_items_product_id ON quotation_items(product_id);

-- ============================================================================
-- 16. ORDERS TABLE (Depends on Quotations, Companies, and Suppliers)
-- ============================================================================
CREATE TABLE orders (
                        id bigint generated by default as identity
        primary key,
                        order_number VARCHAR(255) NOT NULL UNIQUE,
                        quotation_id BIGINT,
                        company_id BIGINT NOT NULL,
                        supplier_id BIGINT NOT NULL,
                        status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
                        subtotal DECIMAL(10, 2) NOT NULL,
                        tax_amount DECIMAL(10, 2) NOT NULL,
                        total_amount DECIMAL(10, 2) NOT NULL,
                        currency VARCHAR(10) DEFAULT 'TRY',
                        delivery_address TEXT,
                        expected_delivery_date DATE,
                        actual_delivery_date DATE,
                        notes TEXT,
                        invoice_number VARCHAR(255),
                        tracking_number VARCHAR(255),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP,
                        created_by BIGINT,
                        updated_by BIGINT,
                        is_active BOOLEAN DEFAULT TRUE,
                        CONSTRAINT fk_orders_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE SET NULL,
                        CONSTRAINT fk_orders_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
);

CREATE INDEX idx_orders_order_number ON orders(order_number);
CREATE INDEX idx_orders_quotation_id ON orders(quotation_id);
CREATE INDEX idx_orders_company_id ON orders(company_id);
CREATE INDEX idx_orders_supplier_id ON orders(supplier_id);
CREATE INDEX idx_orders_status ON orders(status);

-- ============================================================================
-- 17. ORDER ITEMS TABLE (Depends on Orders, Products, and Product Variants)
-- ============================================================================
CREATE TABLE order_items (
                             id bigint generated by default as identity
        primary key,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT,
                             product_variant_id BIGINT,
                             item_name VARCHAR(255) NOT NULL,
                             quantity INTEGER NOT NULL,
                             unit_price DECIMAL(10, 2) NOT NULL,
                             total_price DECIMAL(10, 2) NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP,
                             created_by BIGINT,
                             updated_by BIGINT,
                             is_active BOOLEAN DEFAULT TRUE,
                             CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                             CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
                             CONSTRAINT fk_order_items_product_variant FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE SET NULL
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_order_items_product_variant_id ON order_items(product_variant_id);

-- ============================================================================
-- 18. PRODUCT PAYMENTS TABLE (Depends on Orders)
-- ============================================================================
CREATE TABLE product_payments (
                                  id bigint generated by default as identity
        primary key,
                                  order_id BIGINT NOT NULL UNIQUE,
                                  payment_method VARCHAR(50) NOT NULL,
                                  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
                                  amount DECIMAL(10, 2) NOT NULL,
                                  currency VARCHAR(10) DEFAULT 'TRY',
                                  transaction_id VARCHAR(255),
                                  paid_at TIMESTAMP,
                                  notes TEXT,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP,
                                  created_by BIGINT,
                                  updated_by BIGINT,
                                  is_active BOOLEAN DEFAULT TRUE,
                                  CONSTRAINT fk_product_payments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_payments_order_id ON product_payments(order_id);
CREATE INDEX idx_product_payments_status ON product_payments(status);
CREATE INDEX idx_product_payments_transaction_id ON product_payments(transaction_id);

-- ============================================================================
-- 19. SUPPLIER RATINGS TABLE (Depends on Suppliers, Companies, and Orders)
-- ============================================================================
CREATE TABLE supplier_ratings (
                                  id bigint generated by default as identity
        primary key,
                                  supplier_id BIGINT NOT NULL,
                                  company_id BIGINT NOT NULL,
                                  order_id BIGINT NOT NULL,
                                  delivery_rating INTEGER NOT NULL,
                                  quality_rating INTEGER NOT NULL,
                                  communication_rating INTEGER NOT NULL,
                                  comment TEXT,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP,
                                  created_by BIGINT,
                                  updated_by BIGINT,
                                  is_active BOOLEAN DEFAULT TRUE,
                                  CONSTRAINT fk_supplier_ratings_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
                                  CONSTRAINT fk_supplier_ratings_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
                                  CONSTRAINT chk_delivery_rating CHECK (delivery_rating BETWEEN 1 AND 5),
                                  CONSTRAINT chk_quality_rating CHECK (quality_rating BETWEEN 1 AND 5),
                                  CONSTRAINT chk_communication_rating CHECK (communication_rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_supplier_ratings_supplier_id ON supplier_ratings(supplier_id);
CREATE INDEX idx_supplier_ratings_company_id ON supplier_ratings(company_id);
CREATE INDEX idx_supplier_ratings_order_id ON supplier_ratings(order_id);

-- ============================================================================
-- 20. PRODUCT CONVERSATIONS TABLE (Depends on Companies, Suppliers, Products, Quotations, Orders)
-- ============================================================================
CREATE TABLE product_conversations (
                                       id bigint generated by default as identity
        primary key,
                                       company_id BIGINT NOT NULL,
                                       supplier_id BIGINT NOT NULL,
                                       product_id BIGINT,
                                       quotation_id BIGINT,
                                       order_id BIGINT,
                                       message_type VARCHAR(50),
                                       subject VARCHAR(255) NOT NULL,
                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP,
                                       created_by BIGINT,
                                       updated_by BIGINT,
                                       is_active BOOLEAN DEFAULT TRUE,
                                       CONSTRAINT fk_product_conversations_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
                                       CONSTRAINT fk_product_conversations_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
                                       CONSTRAINT fk_product_conversations_quotation FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE SET NULL,
                                       CONSTRAINT fk_product_conversations_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
);

CREATE INDEX idx_product_conversations_company_id ON product_conversations(company_id);
CREATE INDEX idx_product_conversations_supplier_id ON product_conversations(supplier_id);
CREATE INDEX idx_product_conversations_product_id ON product_conversations(product_id);
CREATE INDEX idx_product_conversations_quotation_id ON product_conversations(quotation_id);
CREATE INDEX idx_product_conversations_order_id ON product_conversations(order_id);

-- ============================================================================
-- 21. PRODUCT MESSAGES TABLE (Depends on Product Conversations and Users)
-- ============================================================================
CREATE TABLE product_messages (
                                  id bigint generated by default as identity
        primary key,
                                  conversation_id BIGINT NOT NULL,
                                  sender_user_id BIGINT NOT NULL,
                                  content TEXT NOT NULL,
                                  attachment_url TEXT,
                                  is_read BOOLEAN NOT NULL DEFAULT FALSE,
                                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP,
                                  created_by BIGINT,
                                  updated_by BIGINT,
                                  is_active BOOLEAN DEFAULT TRUE,
                                  CONSTRAINT fk_product_messages_conversation FOREIGN KEY (conversation_id) REFERENCES product_conversations(id) ON DELETE CASCADE
);

CREATE INDEX idx_product_messages_conversation_id ON product_messages(conversation_id);
CREATE INDEX idx_product_messages_sender_user_id ON product_messages(sender_user_id);
CREATE INDEX idx_product_messages_is_read ON product_messages(is_read);

-- ============================================================================
-- 22. NOTIFICATIONS TABLE (Depends on Users)
-- ============================================================================
CREATE TABLE supply_notifications (
                                      id bigint generated by default as identity
        primary key,
                                      user_id BIGINT NOT NULL,
                                      title VARCHAR(255) NOT NULL,
                                      message TEXT NOT NULL,
                                      notification_type VARCHAR(50) NOT NULL,
                                      is_read BOOLEAN NOT NULL DEFAULT FALSE,
                                      reference_id BIGINT,
                                      reference_type VARCHAR(50),
                                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      read_at TIMESTAMP,
                                      updated_at TIMESTAMP,
                                      created_by BIGINT,
                                      updated_by BIGINT,
                                      is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_supply_notifications_user_id ON supply_notifications(user_id);
CREATE INDEX idx_supply_notifications_is_read ON supply_notifications(is_read);
CREATE INDEX idx_supply_notifications_notification_type ON supply_notifications(notification_type);
CREATE INDEX idx_supply_notifications_reference ON supply_notifications(reference_type, reference_id);

-- ============================================================================
-- COMMENTS AND DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE suppliers IS 'Stores supplier/vendor information';
COMMENT ON TABLE categories IS 'Hierarchical product categories with self-referencing parent relationship';
COMMENT ON TABLE products IS 'Main product catalog with pricing and stock information';
COMMENT ON TABLE rfqs IS 'Request for Quotation - purchasing requests from companies';
COMMENT ON TABLE quotations IS 'Supplier responses to RFQs with pricing and terms';
COMMENT ON TABLE orders IS 'Confirmed purchase orders created from approved quotations';
COMMENT ON TABLE product_payments IS 'Payment information for orders';
COMMENT ON TABLE supplier_ratings IS 'Company ratings for suppliers based on order performance';
COMMENT ON TABLE product_conversations IS 'Communication threads between companies and suppliers';
COMMENT ON TABLE supply_notifications IS 'System notifications for supply chain events';