-- Flyway Migration: HR Insan Kaynakları Modülü Tabloları
-- Öğretmen profilleri, iş ilanları, başvurular ve bildirimler

-- ============================================================================
-- 1. TEACHER_PROFILES (Öğretmen Profilleri)
-- ============================================================================
CREATE TABLE teacher_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    city VARCHAR(50),
    branch VARCHAR(100),
    education_level VARCHAR(50),
    experience_years INTEGER,
    bio TEXT,
    profile_photo_url VARCHAR(500),
    cv_url VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_teacher_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_teacher_profiles_user_id ON teacher_profiles(user_id);
CREATE INDEX idx_teacher_profiles_email ON teacher_profiles(email);
CREATE INDEX idx_teacher_profiles_branch ON teacher_profiles(branch);

-- ============================================================================
-- 2. JOB_POSTINGS (İş İlanları)
-- ============================================================================
CREATE TABLE job_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    position_title VARCHAR(200) NOT NULL,
    branch VARCHAR(100) NOT NULL,
    employment_type VARCHAR(50),
    start_date DATE,
    contract_duration VARCHAR(100),
    required_experience_years INTEGER,
    required_education_level VARCHAR(50),
    salary_min INTEGER,
    salary_max INTEGER,
    show_salary BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    application_deadline DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_job_postings_campus FOREIGN KEY (school_id) REFERENCES campuses(id) ON DELETE CASCADE
);

CREATE INDEX idx_job_postings_school_id ON job_postings(school_id);
CREATE INDEX idx_job_postings_status ON job_postings(status);
CREATE INDEX idx_job_postings_branch ON job_postings(branch);
CREATE INDEX idx_job_postings_application_deadline ON job_postings(application_deadline);

-- ============================================================================
-- 3. JOB_POSTING_PROVINCES (İlan-İl İlişkisi - Many-to-Many)
-- ============================================================================
CREATE TABLE job_posting_provinces (
    job_posting_id BIGINT NOT NULL,
    province_id BIGINT NOT NULL,
    PRIMARY KEY (job_posting_id, province_id),
    CONSTRAINT fk_job_posting_provinces_job FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_job_posting_provinces_province FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE
);

CREATE INDEX idx_job_posting_provinces_province ON job_posting_provinces(province_id);

-- ============================================================================
-- 4. TEACHER_PROFILE_PROVINCES (Öğretmen-İl Tercihi - Many-to-Many)
-- ============================================================================
CREATE TABLE teacher_profile_provinces (
    teacher_profile_id BIGINT NOT NULL,
    province_id BIGINT NOT NULL,
    PRIMARY KEY (teacher_profile_id, province_id),
    CONSTRAINT fk_teacher_profile_provinces_teacher FOREIGN KEY (teacher_profile_id) REFERENCES teacher_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_teacher_profile_provinces_province FOREIGN KEY (province_id) REFERENCES provinces(id) ON DELETE CASCADE
);

CREATE INDEX idx_teacher_profile_provinces_province ON teacher_profile_provinces(province_id);

-- ============================================================================
-- 5. APPLICATIONS (Başvurular)
-- ============================================================================
CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    cover_letter TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    is_withdrawn BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_applications_job_posting FOREIGN KEY (job_posting_id) REFERENCES job_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_teacher FOREIGN KEY (teacher_id) REFERENCES teacher_profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_applications_job_posting_id ON applications(job_posting_id);
CREATE INDEX idx_applications_teacher_id ON applications(teacher_id);
CREATE INDEX idx_applications_status ON applications(status);

-- ============================================================================
-- 6. APPLICATION_NOTES (Başvuru Notları)
-- ============================================================================
CREATE TABLE application_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    note_text TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_application_notes_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_application_notes_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_application_notes_application_id ON application_notes(application_id);

-- ============================================================================
-- 7. APPLICATION_DOCUMENTS (Başvuru Belgeleri)
-- ============================================================================
CREATE TABLE application_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    document_name VARCHAR(200) NOT NULL,
    document_url VARCHAR(500) NOT NULL,
    document_type VARCHAR(50),
    file_size BIGINT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_application_documents_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
);

CREATE INDEX idx_application_documents_application_id ON application_documents(application_id);

-- ============================================================================
-- 8. NOTIFICATIONS (HR Bildirimleri)
-- Not: supply_notifications'tan farklı olarak HR modülü için
-- ============================================================================
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    application_id BIGINT,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(30) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE SET NULL
);

CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_application_id ON notifications(application_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_type ON notifications(type);

-- ============================================================================
-- COMMENTS
-- ============================================================================
COMMENT ON TABLE teacher_profiles IS 'Öğretmen profilleri - kullanıcı ile 1:1';
COMMENT ON TABLE job_postings IS 'Okul iş ilanları';
COMMENT ON TABLE applications IS 'Öğretmen başvuruları';
COMMENT ON TABLE application_notes IS 'Başvuru üzerine HR notları';
COMMENT ON TABLE application_documents IS 'Başvuru belgeleri (CV, diploma vb.)';
COMMENT ON TABLE notifications IS 'HR modülü bildirimleri';
