-- Flyway Migration: Webinar/Etkinlik Modülü Tabloları
-- Etkinlik kategorileri, düzenleyenler, etkinlikler ve kayıtlar

-- ============================================================================
-- 1. EVENT_CATEGORIES (Etkinlik Kategorileri)
-- ============================================================================
CREATE TABLE event_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(50),
    display_order INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX idx_event_categories_slug ON event_categories(slug);
CREATE INDEX idx_event_categories_is_active ON event_categories(is_active);
CREATE INDEX idx_event_categories_display_order ON event_categories(display_order);

-- ============================================================================
-- 2. EVENT_ORGANIZERS (Etkinlik Düzenleyenler)
-- ============================================================================
CREATE TABLE event_organizers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    type VARCHAR(30) NOT NULL,
    description TEXT,
    logo_url VARCHAR(500),
    website VARCHAR(300),
    email VARCHAR(100),
    phone VARCHAR(20),
    address TEXT,
    city VARCHAR(50),
    social_media_links TEXT,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    CONSTRAINT fk_event_organizers_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_event_organizers_slug ON event_organizers(slug);
CREATE INDEX idx_event_organizers_type ON event_organizers(type);
CREATE INDEX idx_event_organizers_created_by ON event_organizers(created_by_user_id);

-- ============================================================================
-- 3. ORGANIZER_CONTACTS (Düzenleyen İletişim Kişileri)
-- ============================================================================
CREATE TABLE organizer_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    title VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    can_create_events BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_organizer_contacts_organizer FOREIGN KEY (organizer_id) REFERENCES event_organizers(id) ON DELETE CASCADE,
    CONSTRAINT fk_organizer_contacts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_organizer_contacts_organizer ON organizer_contacts(organizer_id);
CREATE INDEX idx_organizer_contacts_user ON organizer_contacts(user_id);

-- ============================================================================
-- 4. EVENTS (Etkinlikler)
-- ============================================================================
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    event_type VARCHAR(30) NOT NULL,
    delivery_format VARCHAR(20) NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    max_capacity INTEGER,
    location VARCHAR(300),
    online_link VARCHAR(500),
    target_audience VARCHAR(200),
    speaker_name VARCHAR(100),
    speaker_bio TEXT,
    cover_image_url VARCHAR(500),
    registration_deadline TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    auto_approve_registration BOOLEAN NOT NULL DEFAULT TRUE,
    certificate_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    certificate_template_url VARCHAR(500),
    category_id BIGINT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_events_organizer FOREIGN KEY (organizer_id) REFERENCES event_organizers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES event_categories(id) ON DELETE SET NULL
);

CREATE INDEX idx_events_organizer ON events(organizer_id);
CREATE INDEX idx_events_created_by ON events(created_by_user_id);
CREATE INDEX idx_events_category ON events(category_id);
CREATE INDEX idx_events_status ON events(status);
CREATE INDEX idx_events_start_date_time ON events(start_date_time);
CREATE INDEX idx_events_event_type ON events(event_type);

-- ============================================================================
-- 5. EVENT_REGISTRATIONS (Etkinlik Kayıtları)
-- ============================================================================
CREATE TABLE event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    registration_note TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attended BOOLEAN NOT NULL DEFAULT FALSE,
    attendance_marked_at TIMESTAMP,
    attendance_marked_by_user_id BIGINT,
    certificate_url VARCHAR(500),
    certificate_generated_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_event_registrations_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_registrations_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_registrations_attendance_marked_by FOREIGN KEY (attendance_marked_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT unique_event_teacher_registration UNIQUE (event_id, teacher_id)
);

CREATE INDEX idx_event_registrations_event ON event_registrations(event_id);
CREATE INDEX idx_event_registrations_teacher ON event_registrations(teacher_id);
CREATE INDEX idx_event_registrations_status ON event_registrations(status);
