-- Öğretmen eğitim geçmişi (lisans, yüksek lisans, doktora vb.)
CREATE TABLE teacher_education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_profile_id BIGINT NOT NULL,
    education_level VARCHAR(50) NOT NULL,
    institution VARCHAR(200) NOT NULL,
    department VARCHAR(200),
    start_year INTEGER,
    end_year INTEGER,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_teacher_education_profile FOREIGN KEY (teacher_profile_id) REFERENCES teacher_profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_teacher_education_profile ON teacher_education(teacher_profile_id);

-- Öğretmen iş tecrübesi (kurum, görev, giriş/çıkış tarihi)
CREATE TABLE teacher_experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_profile_id BIGINT NOT NULL,
    institution VARCHAR(200) NOT NULL,
    role_title VARCHAR(200) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_teacher_experience_profile FOREIGN KEY (teacher_profile_id) REFERENCES teacher_profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_teacher_experience_profile ON teacher_experience(teacher_profile_id);

COMMENT ON TABLE teacher_education IS 'Öğretmen eğitim bilgileri (lisans, yüksek lisans, doktora)';
COMMENT ON TABLE teacher_experience IS 'Öğretmen iş tecrübesi (kurum, görev, tarihler)';
