-- V001__Create_institution_type_groups_table.sql
CREATE TABLE institution_type_groups (
                                         id  bigint generated by default as identity
                                             primary key,
                                         name VARCHAR(255) NOT NULL UNIQUE,
                                         display_name VARCHAR(255) NOT NULL,
                                         description TEXT,
                                         icon_url VARCHAR(500),
                                         color_code VARCHAR(50),
                                         sort_order INT DEFAULT 0,
                                         default_properties JSON,
                                         created_at timestamp(6),
                                         updated_at timestamp(6),
                                         created_by bigint,
                                         updated_by bigint,
                                         is_active boolean DEFAULT TRUE
);

-- Add indexes for better performance
CREATE INDEX idx_institution_type_groups_name ON institution_type_groups(name);
CREATE INDEX idx_institution_type_groups_sort_order ON institution_type_groups(sort_order);


-- V003__Create_property_group_types_table.sql
CREATE TABLE property_group_types (
                                      id  bigint generated by default as identity
                                          primary key,
                                      name VARCHAR(255) NOT NULL,
                                      display_name VARCHAR(255) NOT NULL,
                                      institution_type_id bigint NOT NULL,
                                      sort_order INT DEFAULT 0,
                                      created_at timestamp(6),
                                      updated_at timestamp(6),
                                      created_by bigint,
                                      updated_by bigint,
                                      is_active boolean DEFAULT TRUE,

    -- Foreign key constraint
                                      CONSTRAINT fk_property_group_types_institution_type
                                          FOREIGN KEY (institution_type_id)
                                              REFERENCES institution_types(id)
                                              ON DELETE CASCADE ON UPDATE CASCADE
);

-- Add indexes for better performance
CREATE INDEX idx_property_group_types_name ON property_group_types(name);
CREATE INDEX idx_property_group_types_institution_type_id ON property_group_types(institution_type_id);

-- V004__Create_property_types_table.sql
CREATE TABLE property_types (
                                id  bigint generated by default as identity
                                    primary key,
                                name VARCHAR(255) NOT NULL,
                                display_name VARCHAR(255) NOT NULL,
                                property_group_type_id bigint NOT NULL,
                                sort_order INT DEFAULT 0,
                                created_at timestamp(6),
                                updated_at timestamp(6),
                                created_by bigint,
                                updated_by bigint,
                                is_active boolean DEFAULT TRUE,

    -- Foreign key constraint
                                CONSTRAINT fk_property_types_property_group_type
                                    FOREIGN KEY (property_group_type_id)
                                        REFERENCES property_group_types(id)
                                        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Add indexes for better performance
CREATE INDEX idx_property_types_name ON property_types(name);
CREATE INDEX idx_property_types_property_group_type_id ON property_types(property_group_type_id);



-- V002__Add_institution_type_group_id_to_institution_types.sql
-- Mevcut institution_types tablosuna institution_type_group_id alanını ekle

ALTER TABLE institution_types
    ADD COLUMN institution_type_group_id BIGINT;

-- Foreign key constraint ekle
ALTER TABLE institution_types
    ADD CONSTRAINT fk_institution_types_group
        FOREIGN KEY (institution_type_group_id)
            REFERENCES institution_type_groups(id)
            ON DELETE SET NULL ON UPDATE CASCADE;

-- Index ekle
CREATE INDEX idx_institution_types_group_id ON institution_types(institution_type_group_id);


